### Github Authorization
GET http://localhost:8080/github HTTP/1.1

### Authenticate User
POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "code": ""
}

### Create Message
POST http://localhost:8080/message HTTP/1.1
Content-Type: application/json

{
    "message": "Test message"
}